#!/usr/bin/env bash
# This script installs Apache and sets up a page with "Hello Holberton" on Alpine Linux.

apk update
apk add apache2
rc-service apache2 start
echo "Hello Holberton" > /var/www/localhost/htdocs/index.html