#!/usr/bin/env bash
# Update the package list and install Nginx
apt-get update -y
apt-get install -y nginx

# Create a custom HTML file for the root directory
echo "<html>
<head>
    <title>Welcome to Holberton School</title>
</head>
<body>
    Holberton School for the win!
</body>
</html>" > /var/www/html/index.html

# Configure the redirection in the Nginx configuration file
sed -i '/server {/a \\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }\n' /etc/nginx/sites-enabled/default

# Test the Nginx configuration
nginx -t

# Restart Nginx to apply changes
service nginx restart
